name: "Validate Syllabus"

on:
  pull_request:
    paths: 
      - "**/syllabus.yml"
      - "!.github/workflows/syllabus.yml"
  push:
    paths: 
      - "**/syllabus.yml"
      - "!.github/workflows/syllabus.yml"


jobs:
  build:
    name: "Check that Syllabus Changes are Acceptable"
    runs-on: ubuntu-latest
    steps:
    - name: "Set $GROUP"
      run: |
        echo "::set-env name=GROUP::$(basename ${{ github.repository }})"

    - name: "Checkout `${{ github.repository }}`"
      uses: actions/checkout@v2

    - name: "Use `autobot` Action to Validate Syllabus Changes"
      uses: ionlights/tasks@v0.5.0.rc1
      id: autobot
      with:
        workdir: /github/workspace
        commands: >- 
          group.validate-syllabus
          group.touch

    - name: "Post `status` as PR Comment"
      uses: mshick/add-pr-comment@v1
      with:
        repo-token: "${{ secrets.UCFAIBOT_PAT }}"
        message: |
          ${{ steps.autobot.outputs.status }}
        allow-repeats: true