name: "Validate Syllabus"

on:
  pull_request:
    paths:
      - "**/syllabus.yml"
      - "!.github/workflows/syllabus.yml"
  push:
    paths:
      - "**/syllabus.yml"
      - "!.github/workflows/syllabus.yml"

jobs:
  update-solutions:
    runs-on: ubuntu-latest
    env:
      GROUP: "core"

    steps:
      # Checkout repositories
      - name: "${{ env.GROUP }}: Checkout latest master branch"
        uses: actions/checkout@v2
        with:
          repository: "ionlights/${{ env.GROUP }}"
          path: "${{ env.GROUP }}"

      - name: "ucfai/tasks: Checkout latest master branch"
        uses: actions/checkout@v2
        with:
          repository: "ionlights/tasks"
          path: "tasks"

      - name: "Setup ucfai/tasks' environment."
        run: |
          conda env create -f tasks/env.production.yml
          conda activate ucfai-tasks
          inv -f ${{ env.GROUP }}/invoke.py -l

      - name: Purposely Fail
        run: |
          inv -f ${{ env.GROUP }}/invoke.py syllabus.parse
          exit -1
