name: "Validate Syllabus"

on:
  pull_request:
    paths: 
      - "**/syllabus.yml"
    paths-ignore:
      - ".github/workflows"
  push:
    paths: 
      - "**/syllabus.yml"
    paths-ignore:
      - ".github/workflows"

jobs:
  update-solutions:
    runs-on: ubuntu-latest
    env:
      GROUP: "core"

    steps:
      # Checkout repositories
      - name: "${{ env.GROUP }}: Checkout latest master branch"
        uses: actions/checkout@v2
        with:
          repository: "ionlights/${{ env.GROUP }}"
          path: "${{ env.GROUP }}"

      - name: "ucfai/tasks: Checkout latest master branch"
        uses: actions/checkout@v2
        with:
          repository: "ionlights/tasks"
          path: "tasks"

      - name: Purposely Fail
        run: |
          ls -l ${{ env.WORKSPACE }}
          exit -1
