name: "Validate Syllabus"

on:
  pull_request:
    paths: 
      - "**/semester.yml"

jobs:
  update-solutions:
    runs-on: ubuntu-latest
    env:
      GROUP: "core"

    steps:
      # Checkout repositories
      - name: "${GROUP}: Checkout latest master branch"
        uses: actions/checkout@v2
        with:
          repository: "ionlights/${GROUP}"
          path: "${GROUP}"

      - name: "ucfai/tasks: Checkout latest master branch"
        uses: actions/checkout@v2
        with:
          repository: "ionlights/tasks"
          path: "tasks"

      - name: Purposely Fail
        run: |
          ls -l ${WORKSPACE}
          exit -1
